### PR TITLE
replaced tab with spaces and updated print statements to be compatibl…

### PR DESCRIPTION
**Pull request by georgebzheng**
…e with Python3

### CODE REVIEW

**Comment by mwes** [comment]
FYI @johnfonner @mwvaughn George (from Netrias) found this issue working through the SD2 documentation (specifically the auth-switch command)

**Comment by alejandrox1** [comment]
@georgebzheng @mwes how did you come across bin/libs/python/richtext.py ? Where is it used?

**Comment by mwes** [comment]
This occurs for me when running the CLI command `auth-switch`

**Comment by alejandrox1** [comment]
@mwes can you post the error message? Along with the version of python that you are using?

**Comment by mwes** [comment]
Sure thing. Example below. I am using python 3.6.4
```auth-switch
  File "/Users/markweston/Documents/sd2e_new_cli/sd2e-cloud-cli/bin/libs/python/richtext.py", line 17
    result="| "
              ^
TabError: inconsistent use of tabs and spaces in indentation```

This is pretty easy to verify in the original source - you can see the mix of tabs and spaces:
![image](https://user-images.githubusercontent.com/5033275/45438576-7edb3180-b685-11e8-9ee4-f9b934f03430.png)

After you fix those issues, the print statement will complain.

**Comment by alejandrox1** [comment]
@mwes does the error persist if you use python 2.X?

**Comment by mwes** [comment]
I get a different error on a py2 virtualenv. I am not seeing errors with other CLI commands, just this one. Regardless of py2/py3, I wouldn't be mixing tabs and spaces in a python file, and the change to print() is forward looking for python3 compatibility, if this is of interest.

```
(py2) ➜  ~ auth-switch         
Unable to read /Users/markweston/.agave/current#name
Unable to read /Users/markweston/.agave/'basestring'
Unable to read /Users/markweston/.agave/is
Unable to read /Users/markweston/.agave/not
Unable to read /Users/markweston/.agave/defined#name
Unable to read /Users/markweston/.agave/'basestring'
Unable to read /Users/markweston/.agave/is
Unable to read /Users/markweston/.agave/not
Unable to read /Users/markweston/.agave/defined
list index out of range
(py2) ➜  ~ auth-check 
tenant: sd2e
username: mweston
time left: 13897 seconds
expires at: Wed Sep 12 16:22:05 EDT 2018
```

**Comment by alejandrox1** [comment]
@mwes haha that's a cool error. More importably, thank you for all your feedback!
I will leave this pr open for a couple more weeks while we work on the next release and merge it.

**Comment by alejandrox1** [comment]
Closing this pr because of #56

**Comment by mwes** [comment]
@alejandrox1 can you clarify? https://github.com/TACC-Cloud/agave-cli/issues/56 has no development against it from what I can see.

**Pull request closed without merging**
